# Generated by Django 4.2.1 on 2023-10-21 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='album',
            name='duration_seconds',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='album',
            name='trackCount',
            field=models.IntegerField(default=None),
        ),
    ]
