# Generated by Django 4.2.1 on 2023-10-21 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_album_description_album_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='duration_seconds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='album',
            name='trackCount',
            field=models.IntegerField(),
        ),
    ]
