# Generated by Django 4.2.1 on 2023-10-21 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_album_description_alter_album_duration_seconds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='created',
        ),
    ]
