# Generated by Django 4.2.1 on 2023-08-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_photo_album_cover_alter_album_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
