# Generated by Django 3.2.18 on 2023-08-12 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20230812_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='cover',
            field=models.ImageField(upload_to='photos'),
        ),
        migrations.AlterField(
            model_name='artist',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
