# Generated by Django 4.2.1 on 2023-11-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_music_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-year']},
        ),
    ]
