# Generated by Django 4.2.1 on 2023-08-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20230812_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(to='home.music'),
        ),
    ]
