# Generated by Django 4.2.1 on 2023-11-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_album_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='track',
            field=models.FileField(upload_to='audios'),
        ),
    ]
