# Generated by Django 4.2.1 on 2023-08-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_playlist_musics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='ispublick',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(default=None, to='home.music'),
        ),
    ]
