# Generated by Django 4.2.1 on 2023-08-14 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_playlist_ispublick_alter_playlist_musics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='musics',
            field=models.ManyToManyField(null=None, to='home.music'),
        ),
    ]
